apiVersion: backstage.io/v1alpha1
kind: System
metadata: { name: matchday, description: MatchDay enterprise platform }
spec: { owner: platform-team, domain: matchday }
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata: { name: matchday }
spec: { owner: platform-team }
