global:
  novuVersion: 1.0.0
api: { ingress: { enabled: true, hosts: [{ host: novu-api.matchday.internal }] } }
web: { ingress: { enabled: true, hosts: [{ host: novu.matchday.internal }] } }
mongodb: { enabled: true }
redis:   { enabled: true }
