apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-service
  namespace: matchday
  labels: { app.kubernetes.io/name: catalogue-service, matchday.io/domain: merchandise }
data:
  LOG_LEVEL: info
  PORT: "50280"
