apiVersion: v1
kind: ConfigMap
metadata:
  name: responsible-gambling
  namespace: matchday
  labels: { app.kubernetes.io/name: responsible-gambling, matchday.io/domain: betting }
data:
  LOG_LEVEL: info
  PORT: "50243"
