apiVersion: v1
kind: Service
metadata:
  name: responsible-gambling
  namespace: matchday
  labels: { app.kubernetes.io/name: responsible-gambling, matchday.io/domain: betting }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50243, targetPort: 50243 }]
  selector: { app.kubernetes.io/name: responsible-gambling }
