apiVersion: v1
kind: Service
metadata:
  name: personalisation
  namespace: matchday
  labels: { app.kubernetes.io/name: personalisation, matchday.io/domain: merchandise }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50282, targetPort: 50282 }]
  selector: { app.kubernetes.io/name: personalisation }
