apiVersion: v1
kind: ConfigMap
metadata:
  name: fulfilment-service
  namespace: matchday
  labels: { app.kubernetes.io/name: fulfilment-service, matchday.io/domain: merchandise }
data:
  LOG_LEVEL: info
  PORT: "50281"
